---
- hosts: localhost
  become: yes
  become_method: sudo
  vars_files: 
  - us-east-1.yaml 
  tasks: 
  - name: Create instance
    # Basic provisioning example
    # Soft-code exemple for create a ec2 instance
    ec2:
      key_name: "{{key_name}}"
      instance_type: "{{instance_type}}"
      image: "{{image}}"
      group: "{{group}}"
      count: "{{count}}"
      vpc_subnet_id: "{{vpc_subnet_id}}"
      assign_public_ip: "{{assign_public_ip}}"
