---
- hosts: localhost
  become: yes
  become_method: sudo
  vars_files: 
  - us-east-1.yaml 
  tasks: 
  - name: Create instance
    # Basic provisioning example
    ec2:
      key_name: mykey
      instance_type: t2.micro
      image: ami-123456
      wait: yes
      group: webserver
      count: 3
      vpc_subnet_id: subnet-29e63245
      assign_public_ip: yes
