---
- hosts: localhost
  tasks: 

  - name: example using security group rule descriptions
    ec2_group:
      name: Allow_80
      description: sg with rule descriptions
      region: us-east-1
      #state: absent                  #to delete your sec_group from region
      rules:
        - proto: tcp
          ports:
          - 80
          cidr_ip: 0.0.0.0/0
